### ISSUE TITLE
Some Bars aren't showing up

### ISSUE THREAD

**Issue by benesche1** [Scarwolf/pr0p0ll-viewer#12]
3 Bars aren't showing up when viewing this poll: https://pr0p0ll.com/?p=viewresults&id=710
![image](https://user-images.githubusercontent.com/21153818/57584142-5b001200-74d8-11e9-92bb-25720022491c.png)

**Comment by Scarwolf** [comment]
New input on this: As I first thought this is not a bug. To improve this however, the Y axis should not start at the lowest possible value. See #16 

Thanks for reporting :)
