### ISSUE TITLE
Fragenbeschreibung anzeigen

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#13]
Manchmal werden die Fragen nur kurz angeschnitten und in der Fragenbeschreibung dann näher erläutert.
Es wäre gut, wenn diese Beschreibungen mit dargestellt werden würden.
Im JSON unter `qn`/`description` zu finden. _NULL_ wenn nichts vorhanden ist, sonst halt der String.

![grafik](https://user-images.githubusercontent.com/46271553/57971955-0dcae700-7995-11e9-88ce-8b0f516af444.png)
![grafik](https://user-images.githubusercontent.com/46271553/57972004-a2354980-7995-11e9-86d7-2398ceb6476f.png)

**Comment by RundesBalli** [comment]
Ergänzung:
Ggf. sollte man pro Frage einzeln die Option bereitstellen, dass die Beschreibung angezeigt wird.
Manchmal steht auch unnötige Mehrinfo in der Beschreibung, die man nicht im Post haben will.

**Comment by Scarwolf** [comment]
https://github.com/Scarwolf/pr0p0ll-viewer/commit/0ae52045905a8bb4ed97914d082fa8cc75d60b4d
