### ISSUE TITLE
Einzelantwort oder Multiple-Choice

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#14]
Es wäre gut, wenn unter der Fragenbeschreibung (rel.: https://github.com/Scarwolf/pr0p0ll-viewer/issues/13) noch angezeigt werden würde, ob die Frage mit mehreren oder nur mit einer Antwort beantwortet werden konnte.

Zu finden unter `qn`/`answertype`.
Möglichkeiten: `single` für Einzelantwort, `multi` für Mehrfachantwort.

![grafik](https://user-images.githubusercontent.com/46271553/57971983-5edadb00-7995-11e9-9bfd-fa55f2083205.png)
![grafik](https://user-images.githubusercontent.com/46271553/57971987-774af580-7995-11e9-955b-ed5edac4e343.png)

**Comment by Scarwolf** [comment]
https://github.com/Scarwolf/pr0p0ll-viewer/commit/3e719f790e196a5f056b136b745b419ebade3f9f
