### ISSUE TITLE
Ausgabegröße limitieren

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#15]
Die maximale Breite der Ausgabedatei sollte immer limitiert werden, da es sonst zum Problem "falsches grau" kommt.
Die maximale Breite beträgt 1052px.

Hier zu erkennen:
![grafik](https://user-images.githubusercontent.com/46271553/57972273-736ca280-7998-11e9-9ad7-18c3192e28e6.png)

**Comment by Scarwolf** [comment]
Should be fixed. If not, please reopen.

**Comment by Scarwolf** [comment]
Add temporary warning to manually check the image width until a solution is found.

**Comment by RundesBalli** [comment]
Ich weiß nicht in wie weit dich das weiterbringt, aber schau mal beim http://pr0texter.com wie der das macht. Glaube der arbeitet mit html2canvas, vielleicht kann man davon was lernen.

**Comment by Scarwolf** [comment]
Fixed with Commit https://github.com/Scarwolf/pr0p0ll-viewer/commit/db167cfcba63fd76a2b395a8702fe349523ed6d4
