### ISSUE TITLE
Anzahl der Votes anzeigen

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#18]
https://pr0gramm.com/new/3219769
![grafik](https://user-images.githubusercontent.com/46271553/58347351-f04ac100-7e5d-11e9-9fa4-a1e97924a78f.png)
Würde mir wünschen, dass oben drüber die Anzahl der abgegebenen Stimmen steht. Das wäre klasse. (also bei allen, nicht nur bei den markierten)

**Comment by Scarwolf** [comment]
![image](https://user-images.githubusercontent.com/8727623/58754441-2fb58500-84d0-11e9-9787-7c4a49520df5.png)

![image](https://user-images.githubusercontent.com/8727623/58754442-33e1a280-84d0-11e9-83c9-1b15dc6b00ee.png)


Labels are now available on both pie and bar charts.
