### ISSUE TITLE
Option zum Ausblenden der Umfragenbeschreibung anbieten

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#19]
Bei den Fragen geht es ja schon, bei der Umfrage selbst wäre es auch noch hilfreich, da manchmal nur Stuss da drin steht oder eine Kurzeinleitung, welche in Frage 1 näher erläutert wird.
Beispiel hier: https://pr0p0ll.com/?p=viewresults&id=584
Dort steht "Ausführliche Beschreibung in Frage 1.", das interessiert im Kopf niemanden.

**Comment by Scarwolf** [comment]
implemented in https://github.com/Scarwolf/pr0p0ll-viewer/commit/edd7b8aa28b4d29481aafa2fee56aa5bb82debf1
