### ISSUE TITLE
Fehlende Fragenbeschreibung bei Kreisdiagrammen

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#26]
https://pr0gramm.com/new/3237008
https://pr0p0ll.com/?p=viewresults&id=551

![grafik](https://user-images.githubusercontent.com/46271553/58822976-f77d8600-8638-11e9-9650-f6a2abe06b9b.png)

![grafik](https://user-images.githubusercontent.com/46271553/58823012-082dfc00-8639-11e9-9629-144d65c9a4fe.png)

**Comment by Scarwolf** [comment]
Also happens on bar-charts. Desc. is shown but ignored by html2canvas. Fix soon.
