### ISSUE TITLE
Optimize bar chart color event

### ISSUE THREAD

**Issue by Scarwolf** [Scarwolf/pr0p0ll-viewer#27]
Currently, when Changing the bar color, it updates instantly which can be really slow on some systems. Rewrite it so that the colors is only Update on dialog exit.

**Comment by RundesBalli** [comment]
Maybe you should insert a button "apply" which applies the color.

**Comment by Scarwolf** [comment]
Closed. The Color Picker has been replaced with another one that better fits the design and provides smoother feedback.
