### ISSUE TITLE
Ausblendbare Antwortmöglichkeiten

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#28]
https://pr0p0ll.com/?p=viewresults&id=791
Wenn man Frage 1 betrachtet kommt folgendes:
![grafik](https://user-images.githubusercontent.com/46271553/59789748-cce52b80-92ce-11e9-894a-d40a745db35b.png)
Das kleine Diagramm halte ich für in Ordnung, allerdings oben die Buttons ragen bis ins unendliche seitlich heraus.
(liegt am `.btn-group {display:inline-flex;}`, könnte man auf `inline` ändern)

**Comment by Scarwolf** [comment]
Fixed in https://github.com/Scarwolf/pr0p0ll-viewer/commit/658279fefb108a9427f07518ecbb5c2186413030

Thanks!

**Comment by RundesBalli** [comment]
Tested. Works!
