### ISSUE TITLE
Switch Chart Type

### ISSUE THREAD

**Issue by Scarwolf** [Scarwolf/pr0p0ll-viewer#3]
Umschaltmöglichkeit zwischen Balken, Säulen und Kreisdiagramm (Multi Antwort immer Balken/Säulen, Einzelantwort mit Umschaltmöglichkeit)

**Comment by RundesBalli** [comment]
Ergänzung zur Einzelantwort:
Bei Fragen mit mehr als 6-8 Antwortmöglichkeiten wird ein Kreisdiagramm unübersichtlich. Da sollte die Möglichkeit nicht angeboten werden.

**Comment by Scarwolf** [comment]
![image](https://user-images.githubusercontent.com/8727623/58754432-0ac11200-84d0-11e9-9d48-56dc9c136499.png)

Pie Charts are now available. 
They can be selected in the question based settings. The option is only available for questions 8 or less answer possibilities.
