### ISSUE TITLE
Leerraum am Ende

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#32]
Am Ende der Posts wird ein langer leerer Bereich angezeigt.

Probiert mit folgender Umfrage:
https://pr0p0ll.com/?p=viewresults&id=884

Verkleinerte Gesamtansicht:
![grafik](https://user-images.githubusercontent.com/46271553/68901251-dc5d8900-0735-11ea-8ff8-2376862af22e.png)

Auch aufgefallen bei folgendem Post:
https://pr0gramm.com/new/3516600

**Comment by Scarwolf** [comment]
Sollte gefixt sein. Falls der Bug weiterhin auffällt bitte melden.
