### ISSUE TITLE
Prozentangaben hinzufügen

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#35]
![grafik](https://user-images.githubusercontent.com/46271553/86508148-26d36900-bdde-11ea-9411-e2c8a3f8f7b0.png)

https://pr0gramm.com/new/3997907:comment40179744

**Comment by Scarwolf** [comment]
Danke, integriert. Weiterhin werden nun bei Kuchendiagrammen die Werte in der Legende angezeigt. Dies ist nützlich wenn eine Auswahlmöglichkeit so wenig Stimmen hatte dass der Wert nicht in der Chart selbst gerendert werden konnte weil die Fläche zu klein war.
