### ISSUE TITLE
Fehlende X-Achsen-Beschriftungen

### ISSUE THREAD

**Issue by RundesBalli** [Scarwolf/pr0p0ll-viewer#7]
Relatiert: https://github.com/Scarwolf/pr0p0ll-viewer/issues/5

Reproduzierbar mit dieser Umfrage: https://pr0p0ll.com/?p=viewresults&id=711

Der Graph für die Frage "Was für Nüsse isst du?" hat zu viele Antwortmöglichkeiten, sodass nur jede zweite X-Achsen-Beschriftung angezeigt wird.
![grafik](https://user-images.githubusercontent.com/46271553/56456856-72812a80-6372-11e9-8e09-3c66c89d1ecb.png)

**Comment by Scarwolf** [comment]
Danke dir, ist gefixt!
